server.port=8085

spring.messages.basename=lang.messages
spring.thymeleaf.prefix=classpath:/static/

spring.datasource.data=classpath:authors.sql
spring.datasource.url=jdbc:postgresql://postgres:5432/book_shop
spring.datasource.username=mihasya
spring.datasource.password=superman
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.initialization-mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true