server.port=8085

spring.messages.basename=lang.messages
spring.thymeleaf.prefix=classpath:/static/

spring.datasource.data=classpath:authors.sql
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=skillbox
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.initialization-mode=always

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true